version: '3.7'

x-base-dev: &base-dev
  restart: on-failure
  volumes:
    - ./src:/src
    - .:/project

services:

  python:
    <<: *base-dev
    build:
      context: .
      target: application

  application:
    <<: *base-dev
    image: salimfadhley/python_hello_world_server:latest
    build:
      context: .
      target: application
    ports:
      - "8081:80"

volumes:
  database: