version: '3.7'

x-base-dev: &base-dev



services:

  python:
    <<: *base-dev
    build:
      context: .
      target: appinstalled

  application:
    image: salimfadhley/python_hello_world_server:latest
    build:
      context: .
      target: application
    ports:
      - "8081:80"
    restart: on-failure

  dev:
    <<: *base-dev
    image: salimfadhley/python_hello_world_server:latest
    ports:
      - "8081:80"
  volumes:
    - ./src:/src
    - .:/project
