version: '3.7'

services:

  python:
    build:
      context: .
      target: appinstalled

  application:
    image: salimfadhley/python_hello_world_server:latest
    build:
      context: .
      target: application
    ports:
      - "8081:80"
    restart: on-failure

  dev:
    image: salimfadhley/python_hello_world_server:latest
    ports:
      - "8081:80"
    volumes:
      - ./src:/src
      - .:/project
